#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mix_System
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PLC_SQL")]
	public partial class report_ExcelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public report_ExcelDataContext() : 
				base(global::Mix_System.Properties.Settings.Default.sqlReport_String, mappingSource)
		{
			OnCreated();
		}
		
		public report_ExcelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public report_ExcelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public report_ExcelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public report_ExcelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Mix_System_Data> Mix_System_Datas
		{
			get
			{
				return this.GetTable<Mix_System_Data>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mix_System_Data")]
	public partial class Mix_System_Data
	{
		
		private System.Nullable<System.DateTime> _Datetime;
		
		private string _Shift;
		
		private string _Order_ID;
		
		private System.Nullable<double> _Setting_Weight1;
		
		private System.Nullable<double> _Actual_Weight1;
		
		private System.Nullable<double> _Setting_Weight2;
		
		private System.Nullable<double> _Actual_Weight2;
		
		private System.Nullable<int> _Actual_Time_Tron;
		
		public Mix_System_Data()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> Datetime
		{
			get
			{
				return this._Datetime;
			}
			set
			{
				if ((this._Datetime != value))
				{
					this._Datetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shift", DbType="NVarChar(50)")]
		public string Shift
		{
			get
			{
				return this._Shift;
			}
			set
			{
				if ((this._Shift != value))
				{
					this._Shift = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_ID", DbType="NVarChar(50)")]
		public string Order_ID
		{
			get
			{
				return this._Order_ID;
			}
			set
			{
				if ((this._Order_ID != value))
				{
					this._Order_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Setting_Weight1", DbType="Float")]
		public System.Nullable<double> Setting_Weight1
		{
			get
			{
				return this._Setting_Weight1;
			}
			set
			{
				if ((this._Setting_Weight1 != value))
				{
					this._Setting_Weight1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Actual_Weight1", DbType="Float")]
		public System.Nullable<double> Actual_Weight1
		{
			get
			{
				return this._Actual_Weight1;
			}
			set
			{
				if ((this._Actual_Weight1 != value))
				{
					this._Actual_Weight1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Setting_Weight2", DbType="Float")]
		public System.Nullable<double> Setting_Weight2
		{
			get
			{
				return this._Setting_Weight2;
			}
			set
			{
				if ((this._Setting_Weight2 != value))
				{
					this._Setting_Weight2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Actual_Weight2", DbType="Float")]
		public System.Nullable<double> Actual_Weight2
		{
			get
			{
				return this._Actual_Weight2;
			}
			set
			{
				if ((this._Actual_Weight2 != value))
				{
					this._Actual_Weight2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Actual_Time_Tron", DbType="Int")]
		public System.Nullable<int> Actual_Time_Tron
		{
			get
			{
				return this._Actual_Time_Tron;
			}
			set
			{
				if ((this._Actual_Time_Tron != value))
				{
					this._Actual_Time_Tron = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
